# Facebook (+ Wit)
ACCESS_TOKEN = '<<ACCESS_TOKEN>>'
VERIFY_TOKEN = '<<VERIFY_TOKEN>>'
# WIT_AI_ACCESS_TOKEN = 'IKJJJYYVR3X672DHFVS7U7C4L2MQSS2P'
WIT_AI_ACCESS_TOKEN = 'RWMXHJNGE4QRL52HUEFUMLJKFL4L5JOC'

# Offline data sources
FACTS_SOURCE_FILE = 'data/facts.json'
JOKES_SOURCE_FILE = 'data/jokes.json'
QUOTES_SOURCE_FILE = 'data/quotes.json'

# Access token files
SPOTIFY_TOKEN_FILE = 'tokens/spotify_token.json'

# API Keys
GOODREADS_ACCESS_TOKEN = '<<GOODREADS_ACCESS_TOKEN>>'
GOOGLE_MAPS_API_KEY = '<<GOOGLE_MAPS_API_KEY>>'
GOOGLE_URL_SHORTENER_API_KEY = '<<GOOGLE_URL_SHORTENER_API_KEY>>'
MAPQUEST_CONSUMER_KEY = 'oZNzyhAUHiBnR9rhO1dOEFZOYIGUvXGQ'
MUSIXMATCH_API_KEY = '<<MUSIXMATCH_API_KEY>>'
NEWS_API_KEY = 'faf2404f441d472fbafcdcdc4eb89e85'
OPEN_WEATHER_MAP_ACCESS_TOKEN = '944c66bd05b8bf6bfeccb9136d9fcfbd'
SPOTIFY_API_KEY = '<<SPOTIFY_API_KEY>>'
TIME_ZONE_DB_API_KEY = 'J3L4GMA6HYM2'
TMDB_API_KEY = '<<TMDB_API_KEY>>'
WORDS_API_KEY = '<<WORDS_API_KEY>>'
YOUTUBE_DATA_API_KEY = '<<YOUTUBE_DATA_API_KEY>>'

# Local Testing
WIT_LOCAL_DATA = 'local/wit.json'

# Analytics
KEEN_PROJECT_ID = '<<KEEN_PROJECT_ID>>'
KEEN_WRITE_KEY = '<<KEEN_WRITE_KEY>>'
